spin_manifest_version = 2

[application]
name = "spin-http-go-example"
version = "0.2.0"
authors = ["Rui Lopes <rgl@ruilopes.com>"]
description = "Example Spin HTTP Application written in Go"

[[trigger.http]]
route = "/..."
component = "spin-http-go-example"

[component.spin-http-go-example]
source = "spin-http-go-example.wasm"
allowed_outbound_hosts = []
[component.spin-http-go-example.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o spin-http-go-example.wasm"
watch = ["**/*.go", "go.mod"]
